<!doctype html>
<html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ALPHATECH | (주)알파텍</title><meta name="description" content="자동차 와이어 하네스 전문 제조 기업 알파텍 공식 홈페이지">
<link rel="stylesheet" href="styles.css"></head><body>
<header class="header"><div class="container nav-wrap">
<div class="brand"><img src="assets/logo.png" alt="알파텍 로고" class="brand-logo"><div><div class="brand-title">ALPHATECH</div><div class="brand-subtitle">ALPHATECH Co., Ltd. | (주)알파텍</div><div class="brand-caption">Automotive Wiring Harness Manufacturer</div></div></div>
<nav class="nav">
<div class="nav-item"><a href="#about">회사소개</a><div class="dropdown"><a href="#about">대표이사 인사말</a><a href="#vision">경영 비전</a><a href="#history">회사 연혁</a><a href="#organization">조직도</a></div></div>
<div class="nav-item"><a href="#solutions">사업영역</a><div class="dropdown"><a href="#solutions">주요 제품</a><a href="#strength">영업 경쟁력</a><a href="#customers">주요 거래처</a></div></div>
<div class="nav-item"><a href="#process">제조영역</a><div class="dropdown"><a href="#process">생산 공정</a><a href="#facility">생산 설비</a></div></div>
<div class="nav-item"><a href="#rnd">R&D</a><div class="dropdown"><a href="#rnd">R&D 기술 연구</a><a href="#rnd">신규 하네스 개발</a><a href="#rnd">친환경차 대응 기술</a></div></div>
<div class="nav-item"><a href="#esg">ESG</a></div><div class="nav-item"><a href="#certification">인증</a></div><div class="nav-item"><a href="#customers">거래처</a></div><div class="nav-item"><a href="#contact">문의</a></div>
</nav><a class="btn btn-primary nav-btn" href="#contact">상담 문의</a></div></header>

<section class="hero">
<div class="hero-slide active" style="background-image:url('assets/hero1.png')"><div class="overlay"></div><div class="container hero-content"><div class="eyebrow">ALPHATECH</div><h1>Future Mobility Wiring Solution</h1><p>전기차 · 미래차 와이어 하네스 전문 제조</p><div class="hero-actions"><a class="btn btn-primary" href="mailto:lee.seungjun@al-phatech.com">견적 문의</a><a class="btn btn-secondary" href="mailto:alphatech@al-phatech.com">회사소개서</a></div></div></div>
<div class="hero-slide" style="background-image:url('assets/hero2.png')"><div class="overlay"></div><div class="container hero-content"><div class="eyebrow">ALPHATECH</div><h1>Automotive Wiring Harness</h1><p>자동차 전장 하네스 개발 · 샘플 · 양산 대응</p><div class="hero-actions"><a class="btn btn-primary" href="mailto:lee.seungjun@al-phatech.com">견적 문의</a><a class="btn btn-secondary" href="mailto:alphatech@al-phatech.com">회사소개서</a></div></div></div>
<div class="hero-slide" style="background-image:url('assets/hero3.png')"><div class="overlay"></div><div class="container hero-content"><div class="eyebrow">ALPHATECH</div><h1>Precision Manufacturing</h1><p>체계적인 생산 설비 기반 품질 중심 제조</p><div class="hero-actions"><a class="btn btn-primary" href="mailto:lee.seungjun@al-phatech.com">견적 문의</a><a class="btn btn-secondary" href="mailto:alphatech@al-phatech.com">회사소개서</a></div></div></div>
<div class="hero-dots"><button class="dot active" data-slide="0"></button><button class="dot" data-slide="1"></button><button class="dot" data-slide="2"></button></div>
</section>

<main>
<section id="about" class="section"><div class="container two-col"><div><div class="section-tag">MESSAGE</div><h2>대표이사 인사말</h2><div class="message-card"><p>안녕하세요. ㈜알파텍을 찾아주셔서 감사합니다.</p><p>자동차 부품 생산 분야에서 선도적인 위치에 서 있는 와이어 하네스 생산 전문 업체로 차량의 혈관이라 할 수 있는 와이어 하네스 생산에 주력하고 있으며, 1999년 설립 이후 20년 이상의 전문 경험을 바탕으로 자동차 산업의 발전과 혁신에 기여하고 있습니다.</p><p>당사는 자동차용 와이어 하네스 및 친환경 자동차용 하네스를 생산하며 축적된 기술력과 안정적인 품질을 기반으로 고객 만족을 최우선으로 하는 제조 파트너가 되고자 합니다.</p><p>앞으로도 고객 여러분과의 신뢰를 바탕으로 지속적인 기술 개발과 품질 혁신을 통해 자동차 산업 발전에 기여하는 기업이 되겠습니다.</p><div class="message-sign"><span>㈜알파텍 대표이사</span><strong>이창원</strong></div></div></div><div class="image-card"><img src="assets/hero1.png" alt="알파텍 회사 전경"><div class="image-caption"><div>ALPHATECH</div><strong>평택 생산 본사</strong><span>Automotive Wiring Harness Manufacturing</span></div></div></div></section>

<section class="section section-muted"><div class="container cards-3"><div class="info-card"><div class="info-title">안정적 제조 기반</div><p>평택 생산 거점을 기반으로 체계적인 생산 및 출하 프로세스를 운영합니다.</p></div><div class="info-card"><div class="info-title">협업 친화 대응</div><p>개발, 품질, 생산 조직이 연계되어 신규 고객 문의에 실질적으로 대응합니다.</p></div><div class="info-card"><div class="info-title">지속 성장 기반</div><p>자동차 하네스 분야 경험을 바탕으로 지속적인 성장과 신규 고객 확대를 추진합니다.</p></div></div></section>

<section id="vision" class="section"><div class="container"><div class="section-tag">VISION</div><h2>경영 비전 및 방침</h2><div class="banner-image"><img src="assets/vision.png" alt="경영 비전"></div></div></section>
<section id="history" class="section"><div class="container"><div class="section-tag">HISTORY</div><h2>회사 연혁</h2><div class="banner-image"><img src="assets/history.png" alt="회사 연혁"></div></div></section>

<section id="organization" class="section"><div class="container"><div class="section-tag">ORGANIZATION</div><h2>조직도</h2><p class="section-desc">영업, 개발, 생산, 품질 조직이 유기적으로 구성되어 고객 요구 대응부터 양산까지 체계적으로 운영됩니다.</p><div class="grid-3">
<div class="team-card"><h3>영업관리팀</h3><div class="chips"><span>영업관리</span><span>수주관리</span><span>계획수립지시</span><span>납품관리</span><span>원가관리</span><span>창고관리</span></div></div>
<div class="team-card"><h3>구매개발팀</h3><div class="chips"><span>개발관리</span><span>설계관리</span><span>표준관리</span><span>일정관리</span><span>샘플대응</span></div></div>
<div class="team-card"><h3>구매/자재팀</h3><div class="chips"><span>구매관리</span><span>창고관리</span><span>업체관리</span><span>입·출고관리</span><span>재고관리</span><span>표준관리</span></div></div>
<div class="team-card"><h3>조립관리팀</h3><div class="chips"><span>현황관리</span><span>조립지그관리</span><span>조립라인관리</span><span>입·출고관리</span><span>재고관리</span><span>샘플관리</span></div></div>
<div class="team-card"><h3>생산·기술팀</h3><div class="chips"><span>공정관리</span><span>설비관리</span><span>치구관리</span><span>실적관리</span><span>재고관리</span><span>표준관리</span></div></div>
<div class="team-card"><h3>품질팀</h3><div class="chips"><span>공정품질관리</span><span>품질보증</span><span>시스템관리</span><span>검사관리</span><span>시험·측정</span><span>성적서관리</span></div></div>
</div><div class="stats-grid"><div class="stat-card orange"><span>임원</span><strong>5명</strong></div><div class="stat-card blue"><span>관리직</span><strong>12명</strong></div><div class="stat-card cyan"><span>생산직</span><strong>50명</strong></div><div class="stat-card"><span>총 인원</span><strong>67명</strong></div></div></div></section>

<section id="solutions" class="section"><div class="container"><div class="section-tag">BUSINESS</div><h2>주요 제품</h2><div class="grid-4"><div class="feature-card"><h3>자동차 전장 하네스</h3><p>DOOR · FLOOR · CONTROL · FRONT · SEAT 등 차량 주요 전장 하네스 제작 대응</p></div><div class="feature-card"><h3>배터리/센싱 하네스</h3><p>BMA SENSING · VOLT SENSING · BATTERY HARNESS 등 친환경차 대응 제품 생산</p></div><div class="feature-card"><h3>양산 생산 시스템</h3><p>자동 절단 압착, 수동 압착, 조립, 기능 검사, 외관 검사까지 체계적 운영</p></div><div class="feature-card"><h3>검사/품질 보증</h3><p>통전검사기, 비전검사기, 인장력 측정기 등 검사 설비 기반 품질 확보</p></div></div></div></section>

<section id="strength" class="section section-muted"><div class="container"><div class="section-tag">SALES STRENGTH</div><h2>영업 경쟁력</h2><div class="list-grid"><div>와이어 하네스 전문 기업으로 축적된 생산 노하우</div><div>고객 요구 사양에 맞춘 맞춤형 개발 및 샘플 대응</div><div>자동차용 및 친환경차용 하네스 동시 대응 가능</div><div>품질 인증과 검사 설비를 기반으로 한 안정적 납품 체계</div><div>양산 납기 대응이 가능한 공정 운영 및 라인 구성</div><div>신규 거래처 대상 상담 · 개발 · 생산 협업 체계 구축</div></div></div></section>

<section id="process" class="section"><div class="container"><div class="section-tag">PROCESS</div><h2>생산 공정</h2><div class="steps-grid"><div class="step-card"><span>01</span><h3>원자재 수입 검사</h3><p>자재 입고 시 규격 및 품질 상태를 확인하여 생산 안정성을 확보합니다.</p></div><div class="step-card"><span>02</span><h3>절단 · 압착 공정</h3><p>자동 절단 압착 및 수동 압착 라인을 통해 제품 특성에 맞는 공정을 운영합니다.</p></div><div class="step-card"><span>03</span><h3>조립 · 기능 검사</h3><p>오조립, 누락, 오배선, 단선, 쇼트 등을 점검하며 기능 검사를 수행합니다.</p></div><div class="step-card"><span>04</span><h3>외관 검사 · 포장 출하</h3><p>외관, 치수, 포장 사양을 최종 확인한 뒤 고객 납품 기준에 맞춰 출하합니다.</p></div></div></div></section>

<section id="facility" class="section"><div class="container"><div class="section-tag">FACILITY</div><h2>생산 설비 및 공정 라인</h2><p class="section-desc">자동 압착 설비, 조립 라인, 검사 장비, 자재 창고까지 체계적인 생산 인프라를 구축하여 안정적인 양산 대응이 가능합니다.</p><div class="facility-grid">
<div class="facility-card"><img src="assets/facility1.png" alt="자동 압착 설비"><div class="facility-caption"><span>Crimping Line</span><strong>자동 압착 설비</strong></div></div>
<div class="facility-card"><img src="assets/facility2.png" alt="하네스 조립 라인"><div class="facility-caption"><span>Assembly Line</span><strong>하네스 조립 라인</strong></div></div>
<div class="facility-card"><img src="assets/facility3.png" alt="기능 검사 설비"><div class="facility-caption"><span>Inspection</span><strong>기능 검사 설비</strong></div></div>
<div class="facility-card"><img src="assets/facility4.png" alt="자재 창고"><div class="facility-caption"><span>Warehouse</span><strong>자재 창고</strong></div></div>
<div class="facility-card facility-wide"><img src="assets/facility5.png" alt="하네스 생산 라인 전경"><div class="facility-caption"><span>Production Floor</span><strong>하네스 생산 라인 전경</strong></div></div>
</div></div></section>

<section id="rnd" class="section"><div class="container"><div class="section-tag">R&D</div><h2>R&D 기술 연구</h2><p class="section-desc">알파텍은 자동차 전장 하네스 분야의 기술 경쟁력 확보를 위해 지속적인 연구개발을 수행하고 있으며 고객 요구 사양 대응, 샘플 제작, 신규 구조 개발 등 기술 중심 개발 체계를 운영하고 있습니다.</p><div class="cards-3"><div class="feature-card"><h3>신규 하네스 개발</h3><p>고객 요구 사양 기반 신규 하네스 설계 및 샘플 제작 대응</p></div><div class="feature-card"><h3>친환경차 대응 기술</h3><p>BMA 센싱, 배터리 하네스 등 전기차 대응 제품 기술 개발</p></div><div class="feature-card"><h3>기술 품질 개선</h3><p>공정 개선 및 품질 안정화를 위한 지속적인 기술 연구 수행</p></div></div></div></section>

<section id="customers" class="section"><div class="container"><div class="section-tag">CUSTOMERS</div><h2>주요 거래처</h2><div class="logo-grid"><div>INFAC</div><div class="accent">LUCINOVA</div><div>서연이화</div><div>코아시아</div><div>YOU-TECH</div><div>INZI CONTROLS</div><div>DOOWON</div><div>G&amp; 지앤</div><div>상지</div><div>윤진전자</div><div>햇빛일루콤</div><div>협화</div><div>코리아에프티</div><div>동국실업</div><div>유라테크</div></div></div></section>

<section id="esg" class="section section-muted"><div class="container"><div class="section-tag">ESG</div><h2>ESG 경영</h2><p class="section-desc">알파텍은 자동차 와이어 하네스 전문 제조 기업으로서 환경 대응, 사회적 책임, 윤리적 경영 체계를 바탕으로 지속 가능한 제조 경쟁력을 강화하고 있습니다.</p><div class="cards-3"><div class="feature-card"><h3>Environmental</h3><strong>환경 대응</strong><ul><li>친환경 자동차용 하네스 생산 대응</li><li>품질 중심 공정 운영을 통한 자원 효율성 강화</li><li>고객사의 환경 요구사항 및 규제 대응 협업</li></ul></div><div class="feature-card"><h3>Social</h3><strong>사회적 책임</strong><ul><li>안전하고 체계적인 생산 환경 운영</li><li>고객 · 협력사와의 신뢰 기반 파트너십 강화</li><li>품질 안정성과 납기 준수를 통한 고객 만족 실현</li></ul></div><div class="feature-card"><h3>Governance</h3><strong>윤리 · 경영 체계</strong><ul><li>품질 인증 기반의 경영 시스템 운영</li><li>표준화된 공정 및 검사 체계를 통한 신뢰 확보</li><li>지속 가능한 성장과 책임 경영 지향</li></ul></div></div></div></section>

<section id="certification" class="section"><div class="container"><div class="section-tag">CERTIFICATION</div><h2>인증 현황</h2><p class="section-desc">SQ 인증 및 ISO9001 품질 인증, 기업부설연구소 인증 등 다양한 인증을 통해 품질 중심 제조 기업으로서 신뢰성을 확보하고 있습니다.</p><div class="grid-4"><div class="feature-card"><div class="pill">Certification</div><h3>현대 · 기아 SQ 인증</h3><p>고객사 품질 기준에 부합하는 제조 및 품질 운영 체계 확보</p></div><div class="feature-card"><div class="pill">Certification</div><h3>ISO 9001:2015</h3><p>표준화된 품질경영 시스템 기반의 지속적인 품질 개선 운영</p></div><div class="feature-card"><div class="pill">Certification</div><h3>기업부설연구소 인증</h3><p>기술 개발 및 연구 중심의 제조 경쟁력 강화를 위한 연구 체계 운영</p></div><div class="feature-card"><div class="pill">Certification</div><h3>특허 보유</h3><p>커넥터 테스트장치 등 기술 기반 지식재산 확보</p></div></div></div></section>

<section id="contact" class="section"><div class="container contact-wrap"><div><div class="section-tag">CONTACT US</div><h2>신규 거래 및 개발 상담을 환영합니다</h2><p class="section-desc">자동차 와이어 하네스 신규 개발, 샘플 제작, 양산 협업 및 견적 문의는 언제든지 연락 바랍니다.</p><div class="hero-actions"><a class="btn btn-primary" href="mailto:lee.seungjun@al-phatech.com">견적 요청하기</a><a class="btn btn-secondary" href="mailto:alphatech@al-phatech.com">회사소개서 받기</a></div></div><div class="contact-cards"><div class="contact-card"><strong>신규 개발 / 견적 문의</strong><span>이승준 총괄이사</span><a href="mailto:lee.seungjun@al-phatech.com">lee.seungjun@al-phatech.com</a></div><div class="contact-card"><strong>대표 이메일</strong><a href="mailto:alphatech@al-phatech.com">alphatech@al-phatech.com</a></div><div class="contact-card"><strong>전화 문의</strong><a href="tel:01046270820">010-4627-0820 (영업 담당)</a><a href="tel:0316116860">031-611-6860 (대표 번호)</a></div><div class="contact-card"><strong>위치</strong><span>경기도 평택시 서탄면 수월암2길 98-17</span></div><div class="map-wrap"><iframe title="알파텍 위치" src="https://maps.google.com/maps?q=%EA%B2%BD%EA%B8%B0%EB%8F%84%20%ED%8F%89%ED%83%9D%EC%8B%9C%20%EC%84%9C%ED%83%84%EB%A9%B4%20%EC%88%98%EC%9B%94%EC%95%942%EA%B8%B8%2098-17&t=&z=15&ie=UTF8&iwloc=&output=embed" loading="lazy"></iframe></div></div></div></section>
</main>
<script src="script.js"></script></body></html>
